# shell zsh -l -c tmux
background_opacity 1
hide_window_decorations titlebar-only
window_margin_width 0
background_blur 9
linux_display_server wayland
window_padding_width 0
confirm_os_window_close 0
pixel_scroll yes
cursor_trail 3
cursor_trail_start_threshold 2
cursor_trail_decay 0.2 0.6
macos_option_as_alt left
font_size        18.0

# Top | Right | Bottom | Left
window_padding_width 0 10 0 10
 
show_hyperlink_targets yes
detect_urls yes

allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
map ctrl+shift+h show_scrollback

# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output


# BEGIN_KITTY_THEME
# Vague
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='Lilex Nerd Font Mono' postscript_name=LilexNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
