# output=<not set>
font=JetBrainsMono Nerd Font:size=16
dpi-aware=auto
prompt=""
icon-theme=Papirus-Dark
icons-enabled=yes
fields=filename,name,generic
password-character=*
filter-desktop=no
match-mode=fzf
show-actions=no
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
# list-executables-in-path=no

# Layout Settings
# anchor=center
lines=10
width=50
tabs=4
horizontal-pad=18
vertical-pad=8
inner-pad=0
image-size-ratio=1
line-height=30
letter-spacing=0
layer=top
exit-on-keyboard-focus-loss=yes

[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=89b4faff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=89b4faff
counter=7f849cff
border=89b4faff

# Border Settings
[border]
width=2
radius=8

[key-bindings]
delete-line-forward=none
next=Down Control+j
prev=Up Control+k

# dmenu Settings
[dmenu]
# mode=text  # text|index
# exit-immediately-if-empty=no
